[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "https://vikingagm.com/*"
  to = "https://www.vikingagm.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
